# Custom Language File for Launcher Customizer

[ejs.app]
title = "Shy Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/CraftingGamesNet/ShyLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/sQHQU9Nftb"

[ejs.settings]
sourceGithubLink = "https://github.com/CraftingGamesNet/ShyLauncher"
supportLink = "https://github.com/CraftingGamesNet/ShyLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO FAYWYN"
welcomeDescription = ""
welcomeDescCTA = "You are just a few clicks away from Faywyn."
